version: '3'
services:
# 5 simulated nodes, which all run
# the logdag script, a webserver and cron daemon
  cdn01:
    build: .
    environment:
      HOSTNAME: cdn01
    networks:
      main:
        aliases:
          - cdn01
    volumes:
      - /tmp/LogDAGblocks/cdn01:/var/log/blocks
      - $PWD/logdag.py:/main.py:ro # for quick debugging
  cdn02:
    build: .
    environment:
      HOSTNAME: cdn02
    networks:
      main:
        aliases:
          - cdn02
    volumes:
      - /tmp/LogDAGblocks/cdn02:/var/log/blocks
  cdn03:
    build: .
    environment:
      HOSTNAME: cdn03
    networks:
      main:
        aliases:
          - cdn03
    volumes:
      - /tmp/LogDAGblocks/cdn03:/var/log/blocks
  cdn04:
    build: .
    environment:
      HOSTNAME: cdn04
    networks:
      main:
        aliases:
          - cdn04
    volumes:
      - /tmp/LogDAGblocks/cdn04:/var/log/blocks
  cdn05:
    build: .
    environment:
      HOSTNAME: cdn05
    networks:
      main:
        aliases:
          - cdn05
    volumes:
      - /tmp/LogDAGblocks/cdn05:/var/log/blocks

# This tester generates web access logs
# by doing requests to all nodes
  tester:
    build: .
    networks:
      main:
    volumes:
      - $PWD/tester.py:/main.py:ro

# This GUI show the LogDAG,
# overtime the graph grows
  gui:
    image: nginx:alpine
    volumes:
      - $PWD/GUI:/usr/share/nginx/html #default location of nginx container
      - /tmp/LogDAGblocks/cdn01:/usr/share/nginx/html/datadir:ro
    ports:
      - 8080:80

networks:
  main:
